#!/bin/bash
# 🎯 БЪРЗ СТАРТ ЗА ANDROID TV POWERTOOLS
echo "=== 🎯 ANDROID TV POWERTOOLS - QUICK START ==="

echo ""
echo "📋 Available scripts:"
echo "----------------------"
echo "1. 🛡️  tv_health.sh       - System health check"
echo "2. 🎮  adb_master.sh      - ADB remote control" 
echo "3. 🔄  system_updater.sh  - Update all packages"
echo "4. 📡  network_intel.sh   - Network analysis"
echo "5. 🎥  media_master.sh    - Media downloader"
echo "6. 🚀  performance_boost.sh - Performance optimization"
echo "7. 📊  system_report.sh   - System report"
echo "8. 🔒  security_audit.sh  - Security check"
echo "9. 🏗️  install_packages.sh - Install all packages"

echo ""
echo "🚀 Quick commands:"
echo "----------------------"
echo "🔍 Check TV health:    ./tv_health.sh"
echo "📸 Take screenshot:    ./adb_master.sh screen"
echo "🔄 Update system:      ./system_updater.sh"
echo "📡 Scan network:       ./network_intel.sh"
echo "🎥 Download video:     ./media_master.sh 'URL'"
echo "🚀 Boost performance:  ./performance_boost.sh"

echo ""
echo "📖 First time setup:"
echo "----------------------"
echo "1. Run: ./install_packages.sh"
echo "2. Connect TV via ADB: adb connect TV_IP:5555"
echo "3. Check connection: ./tv_health.sh"
echo "4. Enjoy! 🎉"

echo ""
echo "❓ Help:"
echo "----------------------"
echo "All scripts have built-in help: ./script_name.sh"
echo "Check Termux FAQ: https://wiki.termux.com"
